### ISSUE TITLE
the Mission, vision, and objective button

### ISSUE THREAD

**Issue by huda46** [LUCIFER1907/TAREA#1]
hey,

could you please explain us more about the button that leads to the mission vision and objective?, implementing is is actually my part so I have noidea about what kind of button it is.
 
thanks, 

huda

**Comment by palsot** [comment]
hello, 

you need to create a menu, whenever you press the mission option it should lead you to the mission page, and the same for the vision and objective pages. A button icon is not necessary. 

Paloma

**Comment by palsot** [comment]
> 
hello,

you need to create a menu, whenever you press the mission option it should lead you to the mission page, and the same for the vision and objective pages. A button icon is not necessary.

Paloma

**Comment by huda46** [comment]
okay alsoo i had an idea but this one needs javascript, now when you explained me i will check it once again

One more thing, please tell me which font to use for the menu bar orphan or quantium.

thanks :-)

**Comment by huda46** [comment]
Hello,

So there are some points that i want to clarify or to have your opinion about:

1- Regarding the menu bar of the about part, and the image slider: to be able to make them according to your needs, I will have to implement it using JavaScript, I think it is not allowed. so I made it only with css and html but it doesnt look as same as what you asked.

2- Regarding the login and the sign-up pages, can I design it the way I made it, I found it more optimal. you can take a look at it on the pushed login.html because i couldnt take a screen shot and show it here

**Comment by LUCIFER1907** [comment]
You can replace the image slider with a single image covering the entire screen, thank you for bringing it to our notice.

**Comment by huda46** [comment]
Well we did something which is quite fine for a non js code take a look at
it and tell us what you think.
